import 'package:demo/doc/doc_title.dart';
import 'package:demo/widgets/with_value.dart';
import 'package:flutter_vantui/flutter_vantui.dart';
import 'package:tailstyle/tailstyle.dart';
import 'package:flutter/widgets.dart';

class IconPage extends StatelessWidget {
  final Uri location;
  const IconPage(this.location, {super.key});

  @override
  Widget build(BuildContext context) {
    return WithModel("", (model) {
      return Column(children: [
        const DocTitle("Icons"),
        VanInput(
          hint: "Search",
          value: model.value,
          onChange: (v) => model.value = v,
        ),
        Expanded(
          child: CustomScrollView(slivers: [
            SliverGrid(
              delegate: SliverChildListDelegate.fixed(List.of(kVanIconsMap
                  .entries
                  .where((entry) => entry.key.contains(model.value))
                  .map((entry) {
                final label = entry.key, name = entry.value;
                return Column(children: [
                  Expanded(
                    child: FittedBox(
                        child: TailBox().p(10).Container(child: VanIcon(name))),
                  ),
                  TailTypo().font_size(14).text_center().Text(label),
                  const SizedBox(height: 10),
                ]);
              }))),
              gridDelegate: const SliverGridDelegateWithMaxCrossAxisExtent(
                maxCrossAxisExtent: 150,
                childAspectRatio: 1,
              ),
            ),
          ]),
        ),
      ]);
    });
  }
}

const kVanIconsMap = {
  "exchange": VanIcons.exchange,
  "eye": VanIcons.eye,
  "enlarge": VanIcons.enlarge,
  "expand_o": VanIcons.expand_o,
  "eye_o": VanIcons.eye_o,
  "expand": VanIcons.expand,
  "filter_o": VanIcons.filter_o,
  "fire": VanIcons.fire,
  "fail": VanIcons.fail,
  "failure": VanIcons.failure,
  "fire_o": VanIcons.fire_o,
  "flag_o": VanIcons.flag_o,
  "font": VanIcons.font,
  "font_o": VanIcons.font_o,
  "gem_o": VanIcons.gem_o,
  "flower_o": VanIcons.flower_o,
  "gem": VanIcons.gem,
  "gift_card": VanIcons.gift_card,
  "friends": VanIcons.friends,
  "friends_o": VanIcons.friends_o,
  "gold_coin": VanIcons.gold_coin,
  "gold_coin_o": VanIcons.gold_coin_o,
  "good_job_o": VanIcons.good_job_o,
  "gift": VanIcons.gift,
  "gift_o": VanIcons.gift_o,
  "gift_card_o": VanIcons.gift_card_o,
  "good_job": VanIcons.good_job,
  "home_o": VanIcons.home_o,
  "goods_collect": VanIcons.goods_collect,
  "graphic": VanIcons.graphic,
  "goods_collect_o": VanIcons.goods_collect_o,
  "hot_o": VanIcons.hot_o,
  "info": VanIcons.info,
  "hotel_o": VanIcons.hotel_o,
  "info_o": VanIcons.info_o,
  "hot_sale_o": VanIcons.hot_sale_o,
  "hot": VanIcons.hot,
  "like": VanIcons.like,
  "idcard": VanIcons.idcard,
  "invitation": VanIcons.invitation,
  "like_o": VanIcons.like_o,
  "hot_sale": VanIcons.hot_sale,
  "location_o": VanIcons.location_o,
  "location": VanIcons.location,
  "label": VanIcons.label,
  "lock": VanIcons.lock,
  "label_o": VanIcons.label_o,
  "map_marked": VanIcons.map_marked,
  "logistics": VanIcons.logistics,
  "manager": VanIcons.manager,
  "more": VanIcons.more,
  "live": VanIcons.live,
  "manager_o": VanIcons.manager_o,
  "medal": VanIcons.medal,
  "more_o": VanIcons.more_o,
  "music_o": VanIcons.music_o,
  "music": VanIcons.music,
  "new_arrival_o": VanIcons.new_arrival_o,
  "medal_o": VanIcons.medal_o,
  "new_o": VanIcons.new_o,
  "free_postage": VanIcons.free_postage,
  "newspaper_o": VanIcons.newspaper_o,
  "new_arrival": VanIcons.new_arrival,
  "minus": VanIcons.minus,
  "orders_o": VanIcons.orders_o,
  "newbanner": VanIcons.newbanner,
  "paid": VanIcons.paid,
  "notes_o": VanIcons.notes_o,
  "other_pay": VanIcons.other_pay,
  "pause_circle": VanIcons.pause_circle,
  "pause": VanIcons.pause,
  "pause_circle_o": VanIcons.pause_circle_o,
  "peer_pay": VanIcons.peer_pay,
  "pending_payment": VanIcons.pending_payment,
  "passed": VanIcons.passed,
  "plus": VanIcons.plus,
  "phone_circle_o": VanIcons.phone_circle_o,
  "phone_o": VanIcons.phone_o,
  "printer": VanIcons.printer,
  "photo_fail": VanIcons.photo_fail,
  "phone": VanIcons.phone,
  "photo_o": VanIcons.photo_o,
  "play_circle": VanIcons.play_circle,
  "play": VanIcons.play,
  "phone_circle": VanIcons.phone_circle,
  "point_gift_o": VanIcons.point_gift_o,
  "point_gift": VanIcons.point_gift,
  "play_circle_o": VanIcons.play_circle_o,
  "shrink": VanIcons.shrink,
  "photo": VanIcons.photo,
  "qr": VanIcons.qr,
  "qr_invalid": VanIcons.qr_invalid,
  "question_o": VanIcons.question_o,
  "revoke": VanIcons.revoke,
  "replay": VanIcons.replay,
  "service": VanIcons.service,
  "question": VanIcons.question,
  "search": VanIcons.search,
  "refund_o": VanIcons.refund_o,
  "service_o": VanIcons.service_o,
  "scan": VanIcons.scan,
  "share": VanIcons.share,
  "send_gift_o": VanIcons.send_gift_o,
  "share_o": VanIcons.share_o,
  "setting": VanIcons.setting,
  "points": VanIcons.points,
  "photograph": VanIcons.photograph,
  "shop": VanIcons.shop,
  "shop_o": VanIcons.shop_o,
  "shop_collect_o": VanIcons.shop_collect_o,
  "shop_collect": VanIcons.shop_collect,
  "smile": VanIcons.smile,
  "shopping_cart_o": VanIcons.shopping_cart_o,
  "sign": VanIcons.sign,
  "sort": VanIcons.sort,
  "star_o": VanIcons.star_o,
  "smile_comment_o": VanIcons.smile_comment_o,
  "stop": VanIcons.stop,
  "stop_circle_o": VanIcons.stop_circle_o,
  "smile_o": VanIcons.smile_o,
  "star": VanIcons.star,
  "success": VanIcons.success,
  "stop_circle": VanIcons.stop_circle,
  "records": VanIcons.records,
  "shopping_cart": VanIcons.shopping_cart,
  "tosend": VanIcons.tosend,
  "todo_list": VanIcons.todo_list,
  "thumb_circle_o": VanIcons.thumb_circle_o,
  "thumb_circle": VanIcons.thumb_circle,
  "umbrella_circle": VanIcons.umbrella_circle,
  "underway": VanIcons.underway,
  "upgrade": VanIcons.upgrade,
  "todo_list_o": VanIcons.todo_list_o,
  "tv_o": VanIcons.tv_o,
  "underway_o": VanIcons.underway_o,
  "user_o": VanIcons.user_o,
  "vip_card_o": VanIcons.vip_card_o,
  "vip_card": VanIcons.vip_card,
  "send_gift": VanIcons.send_gift,
  "wap_home": VanIcons.wap_home,
  "wap_nav": VanIcons.wap_nav,
  "volume_o": VanIcons.volume_o,
  "video": VanIcons.video,
  "wap_home_o": VanIcons.wap_home_o,
  "volume": VanIcons.volume,
  "warning": VanIcons.warning,
  "weapp_nav": VanIcons.weapp_nav,
  "wechat_pay": VanIcons.wechat_pay,
  "warning_o": VanIcons.warning_o,
  "wechat": VanIcons.wechat,
  "setting_o": VanIcons.setting_o,
  "youzan_shield": VanIcons.youzan_shield,
  "warn_o": VanIcons.warn_o,
  "smile_comment": VanIcons.smile_comment,
  "user_circle_o": VanIcons.user_circle_o,
  "video_o": VanIcons.video_o,
  "add_square": VanIcons.add_square,
  "add": VanIcons.add,
  "arrow_down": VanIcons.arrow_down,
  "arrow_up": VanIcons.arrow_up,
  "arrow": VanIcons.arrow,
  "after_sale": VanIcons.after_sale,
  "add_o": VanIcons.add_o,
  "alipay": VanIcons.alipay,
  "ascending": VanIcons.ascending,
  "apps_o": VanIcons.apps_o,
  "aim": VanIcons.aim,
  "award": VanIcons.award,
  "arrow_left": VanIcons.arrow_left,
  "award_o": VanIcons.award_o,
  "audio": VanIcons.audio,
  "bag_o": VanIcons.bag_o,
  "balance_list": VanIcons.balance_list,
  "back_top": VanIcons.back_top,
  "bag": VanIcons.bag,
  "balance_pay": VanIcons.balance_pay,
  "balance_o": VanIcons.balance_o,
  "bar_chart_o": VanIcons.bar_chart_o,
  "bars": VanIcons.bars,
  "balance_list_o": VanIcons.balance_list_o,
  "birthday_cake_o": VanIcons.birthday_cake_o,
  "bookmark": VanIcons.bookmark,
  "bill": VanIcons.bill,
  "bell": VanIcons.bell,
  "browsing_history_o": VanIcons.browsing_history_o,
  "browsing_history": VanIcons.browsing_history,
  "bookmark_o": VanIcons.bookmark_o,
  "bulb_o": VanIcons.bulb_o,
  "bullhorn_o": VanIcons.bullhorn_o,
  "bill_o": VanIcons.bill_o,
  "calendar_o": VanIcons.calendar_o,
  "brush_o": VanIcons.brush_o,
  "card": VanIcons.card,
  "cart_o": VanIcons.cart_o,
  "cart_circle": VanIcons.cart_circle,
  "cart_circle_o": VanIcons.cart_circle_o,
  "cart": VanIcons.cart,
  "cash_on_deliver": VanIcons.cash_on_deliver,
  "cash_back_record": VanIcons.cash_back_record,
  "cashier_o": VanIcons.cashier_o,
  "chart_trending_o": VanIcons.chart_trending_o,
  "certificate": VanIcons.certificate,
  "chat": VanIcons.chat,
  "clear": VanIcons.clear,
  "chat_o": VanIcons.chat_o,
  "checked": VanIcons.checked,
  "clock": VanIcons.clock,
  "clock_o": VanIcons.clock_o,
  "close": VanIcons.close,
  "closed_eye": VanIcons.closed_eye,
  "circle": VanIcons.circle,
  "cluster_o": VanIcons.cluster_o,
  "column": VanIcons.column,
  "comment_circle_o": VanIcons.comment_circle_o,
  "cluster": VanIcons.cluster,
  "comment": VanIcons.comment,
  "comment_o": VanIcons.comment_o,
  "comment_circle": VanIcons.comment_circle,
  "completed": VanIcons.completed,
  "credit_pay": VanIcons.credit_pay,
  "coupon": VanIcons.coupon,
  "debit_pay": VanIcons.debit_pay,
  "coupon_o": VanIcons.coupon_o,
  "contact": VanIcons.contact,
  "descending": VanIcons.descending,
  "desktop_o": VanIcons.desktop_o,
  "diamond_o": VanIcons.diamond_o,
  "description": VanIcons.description,
  "delete": VanIcons.delete,
  "diamond": VanIcons.diamond,
  "delete_o": VanIcons.delete_o,
  "cross": VanIcons.cross,
  "edit": VanIcons.edit,
  "ellipsis": VanIcons.ellipsis,
  "down": VanIcons.down,
  "discount": VanIcons.discount,
  "ecard_pay": VanIcons.ecard_pay,
  "envelop_o": VanIcons.envelop_o,
  "shield_o": VanIcons.shield_o,
  "guide_o": VanIcons.guide_o,
  "cash_o": VanIcons.cash_o,
  "qq": VanIcons.qq,
  "wechat_moments": VanIcons.wechat_moments,
  "weibo": VanIcons.weibo,
  "link_o": VanIcons.link_o,
  "miniprogram_o": VanIcons.miniprogram_o,
};
