name: demo
description: Flutter Vant UI Demo

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=2.18.6 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  go_router: ^7.0.1
  tailstyle: ^1.1.9
  flutter_syntax_view: ^4.0.0
  tuple: ^2.0.0
  flutter_vantui:
    path: ../vantui

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
