name: Build Test

on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}
      - name: Prerequisite
        run: echo ${{ github.event.pull_request.head.sha }}
      - name: Build Demo Web
        uses: ./.github/actions/build-demo-web
